# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build settings
build:
  os: ubuntu-24.04
  tools:
    python: "3.10"
  commands:
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - find . -path $READTHEDOCS_OUTPUT -prune -o -exec cp -r {} $READTHEDOCS_OUTPUT/html \;
